### ISSUE TITLE
👑 [需求 | Feature] 建议 antd Pro 菜单滚动条更改为像 antd 官网一样鼠标移入显示，更加美观

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design-pro#10330]
### 🥰 需求描述 | Requirements description

建议 antd Pro 菜单滚动条更改为像 antd 官网一样鼠标移入显示，更加美观

### 🧐 解决方案 | Solution

https://ant.design/

### 🚑 其他信息 | Other information

![微信截图_20221029221122](https://user-images.githubusercontent.com/3166799/198836276-4f49ea8e-50cd-4f62-ae3d-3df3905a118f.png)

**Comment by mendellin** [comment]
您好，在antd 6 (umi4)要如何实现这个呢？谢谢

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


解决这个问题可以使用 CSS 来修改滚动条的样式。下面是具体的解决方案步骤：

1. 首先，需要创建一个 CSS 文件，比如命名为 `scrollbar.css`。
2. 在 `scrollbar.css` 文件中，使用 `::-webkit-scrollbar` 伪元素选择器来选择滚动条。
3. 使用 `width` 设置滚动条的宽度，使用 `background-color` 设置滚动条的背景颜色，使用 `border-radius` 设置滚动条的圆角。
4. 使用 `::-webkit-scrollbar-thumb` 伪元素选择器来选择滚动条的滑块。
5. 使用 `background-color` 设置滑块的颜色，使用 `border-radius` 设置滑块的圆角。
6. 在需要引用这个样式文件的地方，比如在入口文件中，使用 `import` 或 `link` 标签将 `scrollbar.css` 引入到项目中。
7. 在菜单组件的样式文件中，添加 `class` 或 `id`，然后在该选择器下应用修改滚动条样式的 CSS。

以下是一个示例的 `scrollbar.css` 文件的代码：

```css
/* scrollbar.css */

/* 滚动条整体样式 */
::-webkit-scrollbar {
  width: 8px;
}

/* 滚动条滑块样式 */
::-webkit-scrollbar-thumb {
  background-color: #c0c0c0;
  border-radius: 4px;
}

/* 滚动条滑块悬停样式 */
::-webkit-scrollbar-thumb:hover {
  background-color: #a0a0a0;
}
```

请根据实际项目中的文件结构和组件样式文件的引用方式，将 `scrollbar.css` 文件引入到项目中，并根据需要修改滚动条的样式。
