### ISSUE TITLE
🧐[问题 | question]请问Menu收宿的宽度怎么改？ 

### ISSUE THREAD

**Issue by xgbnl** [ant-design/ant-design-pro#10390]
### 🧐 问题描述 | Problem description

我在scss文件里让它收缩时强制为48px。但是收宿的时候宽度变化会有延时，看起来不自然

### 💻 示例代码 | Sample code

.ant-menu-inline-collapsed {
  width: 49px !important;
}

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌟 解决方案 | Solution

收缩 Menu 的宽度导致延迟变化的问题可能是由于变化的动画效果在完成之前被打断所致。可以尝试关闭它的 CSS Transition 属性。在组件的 Menu 根元素上添加 `transition: none !important;` 样式。可参考以下示例代码：

```scss
.ant-menu {
  transition: none !important;
}

.ant-menu-inline-collapsed {
  width: 48px !important;
}
```
如果想要添加缓动效果，可以使用 JavaScript 配合 CSS 类名的方式来更精细的控制动画。具体实现方法请参考 Ant Design 官方文档 [Menu Component - Custom Dynamic Trigger](https://ant.design/components/menu-cn/#components-menu-demo-custom-dynamic-trigger) 章节的代码实现。
