### ISSUE TITLE
👑 [需求 | Feature]如何修改 ant-pro-page-container-children-content 24px margin ？有配置项吗？

### ISSUE THREAD

**Issue by woshihuxiangbo** [ant-design/ant-design-pro#10429]
![66ea7fe8dadc37ee97fb01697738d1e](https://user-images.githubusercontent.com/29811324/206665182-5ac242b7-bdfe-475e-b588-706264ea85f1.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，可以通过自定义样式来修改 `ant-pro-page-container-children-content` 的 margin，具体步骤如下：

1. 在项目中创建一个自定义样式文件（如：custom.less）；
2. 在自定义样式文件中添加如下代码：

```less
/* 更改 ant-pro-page-container-children-content 的 margin 为 0 */
@import '~antd/lib/page-header/style/index.less';
@import '~antd/lib/page-header/style/patch.less';

.ant-pro-page-container-children-content {
  margin: 0;
}
```

3. 在需要使用自定义样式的页面中引入该样式文件，示例代码如下：

```jsx
import React from 'react';
import { PageContainer } from '@ant-design/pro-layout';

import './custom.less';

export default () => {
  return (
    <PageContainer>
      {/* 此处为页面内容 */}
    </PageContainer>
  );
};
```

通过以上步骤，即可将 `ant-pro-page-container-children-content` 的 margin 修改为 0。代码中的 `0` 可以根据实际需求进行更改。

若您需要了解更多关于 antd 的样式定制方面的内容，可以参考官方文档中的『CSS 风格和主题』章节：https://ant.design/docs/react/customize-theme-cn。
