### ISSUE TITLE
🧐[问题 | question] 如何修改 ant-pro-page-container-children-content  24px  margin  ？

### ISSUE THREAD

**Issue by woshihuxiangbo** [ant-design/ant-design-pro#10428]
如何修改 ant-pro-page-container-children-content  24px  margin  ？
![66ea7fe8dadc37ee97fb01697738d1e](https://user-images.githubusercontent.com/29811324/206664650-2736a287-7d1f-4b67-b1f6-6f6f262238f1.png)

**Comment by woshihuxiangbo** [comment]
是不是有配置项呢？

**Comment by hooliy** [comment]
![image](https://user-images.githubusercontent.com/3368691/207530880-d565f745-b6e2-46b7-911c-cb4da64bb1d8.png)
使用 token 修改

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您可以通过修改 `ant-pro-page-container-children-content` 的样式，来调整其 24px 的 margin。可以使用 Ant Design Pro 的自定义主题功能，在 `config.less` 中定义新的变量，然后在 `override.less` 中使用这些变量来覆盖默认的样式。

以修改 `ant-pro-page-container-children-content` 的 margin 为例，在 `config.less` 中添加以下变量定义：

```less
// config.less
@page-container-gutter: 24px; // 设置新的 gutter 值
```

然后在 `override.less` 中覆盖 `ant-pro-page-container-children-content` 的样式：

```less
// override.less
@import "~antd/lib/style/themes/default.less"; // 引入 antd 默认主题

// 使用 token 为 margin 设置新值
.ant-pro-page-container-children-content {
  margin: @page-container-gutter 0;
}

// 使用新的 token 设置其他相关样式
.ant-pro-page-header-wrap {
  padding: @page-container-gutter;
}
```

需要注意的是，在 `config.less` 中定义的变量需要使用 `@` 符号，然后可以在 `override.less` 中使用这些变量来修改样式。具体的 tokens 可以在 Ant Design Pro 的自定义主题文档中查看。
