### ISSUE TITLE
🐛 [BUG] 使用 token 更改颜色后，屏幕缩小，菜单背景显示白色

### ISSUE THREAD

**Issue by hooliy** [ant-design/ant-design-pro#10441]
![image](https://user-images.githubusercontent.com/3368691/207530273-b04fde19-5495-4d02-a4cc-c9d2d5bcbd11.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，根据您提供的信息，我们可以初步判断您遇到的问题可能是由于浏览器缩放导致的，而并非您的代码问题。

当页面缩放比例改变时，浏览器会重新计算元素的尺寸和位置。这可能会导致您的 CSS 样式出现错误，菜单的背景颜色显示异常。

我们建议您检查您的 CSS 样式表，确保其中没有基于固定像素值而非可变单位的值。尽量使用 `em`、`rem`、`%` 等相对单位，而非 `px` 等绝对单位。

此外，您可以通过以下 CSS 样式设置强制禁用页面缩放功能：

```css
/* 禁用页面缩放功能 */
body {
  touch-action: pan-x pan-y; /* 禁止双指缩放*/
  -ms-touch-action: pan-x pan-y; /* IE 10 */
  zoom: reset; /* 重置页面缩放 */
  zoom: 1 !important; /* 强制禁用页面缩放 */
  -moz-transform: scale(1,1); /* 火狐浏览器 */
  -moz-transform-origin: top left;
}
```

最后，如果您遇到的问题不是由以上原因造成的，我们建议您提供更多细节或代码示例，以便我们更好地了解并解决问题。
