### ISSUE TITLE
👑 [需求 | Feature]antd升级到5.x后，菜单高亮怎么跟随主题色

### ISSUE THREAD

**Issue by Cyan-Xmw** [ant-design/ant-design-pro#10463]
### 🥰 需求描述 | Requirements description

![image](https://user-images.githubusercontent.com/40554571/209747777-0b99196c-f3a7-45bd-8964-bf8c92eab013.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


根据需求描述可以看出，用户需要将菜单栏的高亮颜色与主题色保持一致，在 antd 5.x 版本中，可以通过修改 Menu 组件的样式来实现这一需求。可以尝试以下方法：

1. 使用 Less 变量重新定义菜单组件的样式

可以根据主题色重新定义菜单组件的样式，如下所示：

```less
@import '~antd/dist/antd.less';

@primary-color: #1890ff; // 修改主题色

.ant-menu-horizontal > .ant-menu-item:hover,  // 菜单栏中单个菜单项 hover 状态下的样式
.ant-menu-horizontal > .ant-menu-item-active, // 菜单栏中单个菜单项激活状态下的样式
.ant-menu-horizontal > .ant-menu-item-selected, // 菜单栏中单个菜单项选中状态下的样式
.ant-menu-horizontal > .ant-menu-item-open, // 菜单栏中单个菜单项展开状态下的样式
.ant-menu-horizontal > .ant-menu-item-selected > a,
.ant-menu-horizontal > .ant-menu-item-open > a {
    color: @primary-color; // 设置菜单栏中单个菜单项的文字颜色
}

.ant-menu-horizontal > .ant-menu-submenu:hover, // 菜单栏中下拉菜单 hover 状态下的样式
.ant-menu-horizontal > .ant-menu-submenu-active, // 菜单栏中下拉菜单激活状态下的样式
.ant-menu-horizontal > .ant-menu-submenu-selected, // 菜单栏中下拉菜单选中状态下的样式
.ant-menu-horizontal > .ant-menu-submenu-open, // 菜单栏中下拉菜单展开状态下的样式
.ant-menu-horizontal > .ant-menu-submenu-selected > a,
.ant-menu-horizontal > .ant-menu-submenu-open > a {
    color: @primary-color; // 设置菜单栏中下拉菜单的文字颜色
}

.ant-anchor-link-active.ant-anchor-link-title { // Anchor 组件在点击导航链接进行跳转时的样式
  color: @primary-color; // 设置 Anchor 组件的文字颜色
}
```

2. 使用 CSS 变量重新定义菜单组件的样式

在 antd 5.x 版本中，我们可以直接使用 CSS 变量来重新定义菜单组件的样式，以下是一个例子：

```css
:root {
  --primary-color: #1890ff; // 修改主题色
}

.ant-menu-horizontal > .ant-menu-item:hover,
.ant-menu-horizontal > .ant-menu-item-active,
.ant-menu-horizontal > .ant-menu-item-selected,
.ant-menu-horizontal > .ant-menu-item-open,
.ant-menu-horizontal > .ant-menu-item-selected > a,
.ant-menu-horizontal > .ant-menu-item-open > a {
  color: var(--primary-color); // 设置菜单栏中单个菜单项的文字颜色为主题色
}

.ant-menu-horizontal > .ant-menu-submenu:hover,
.ant-menu-horizontal > .ant-menu-submenu-active,
.ant-menu-horizontal > .ant-menu-submenu-selected,
.ant-menu-horizontal > .ant-menu-submenu-open,
.ant-menu-horizontal > .ant-menu-submenu-selected > a,
.ant-menu-horizontal > .ant-menu-submenu-open > a {
  color: var(--primary-color); // 设置菜单栏中下拉菜单的文字颜色为主题色
}

.ant-anchor-link-active.ant-anchor-link-title {
  color: var(--primary-color); // 设置 Anchor 组件的文字颜色为主题色
}
```

以上是两种改变菜单栏高亮颜色的方法，需要注意的是，这里只是提供了在 antd 5.x 版本中改变菜单栏高亮颜色的一个思路，具体还需要结合项目实际情况来进行调整和优化。
