### ISSUE TITLE
🐛 [BUG] 界面设置抽屉弹出后关闭按钮消失

### ISSUE THREAD

**Issue by jiabochao** [ant-design/ant-design-pro#10511]
### 🐛 bug 描述

界面设置抽屉弹出后关闭按钮消失

### 📷 复现步骤 | Recurrence steps

![image](https://user-images.githubusercontent.com/16523012/213859604-eca03156-06c0-435b-b02c-1595d67eaa30.png)

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，根据您的描述，这个问题可能是由于编码问题导致的样式问题，可以尝试在样式文件中添加如下代码：

```css
.ant-drawer .ant-drawer-close {
  position: absolute;
  top: 0;
  right: 0;
  z-index: 5;
}
```

文档参考：https://ant.design/components/drawer-cn/

如果问题仍然存在，请检查依赖包与Ant Design Pro版本是否匹配，以及相关组件的使用是否正确。您也可以提出更详细的信息，以便更好地定位和解决问题。
