### ISSUE TITLE
🧐[问题 | question] 如何将标题居中显示

### ISSUE THREAD

**Issue by wushangwei** [ant-design/ant-design-pro#10528]
### 🧐 问题描述 | Problem description

想要做大屏展示页面，请问如何配置使得logo和标题在顶部居中显示呢？

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### ✅ 解决方案 | Solutions

你可以使用 CSS 中的 flex 布局来实现标题居中显示的效果。

在页面的 HTML 文件中，可以将 logo 和标题都放在一个 div 容器中：

```
<div class="header">
  <img src="logo.png" alt="logo">
  <h1 class="title">页面标题</h1>
</div>
```

然后在 CSS 文件中添加以下样式：

```css
.header {
  display: flex; /* 使用 flex 布局 */
  justify-content: center; /* 水平居中 */
  align-items: center; /* 垂直居中 */
}
```

这样就可以实现 logo 和标题在顶部居中显示的效果了。

另外，如果你想要更深入学习 flex 布局的知识，可以参考以下文档：

- [flex 布局教程](https://www.ruanyifeng.com/blog/2015/07/flex-grammar.html)
- [Flex 布局完整指南](https://www.w3cplus.com/css3/a-guide-to-flexbox-new.html)

希望能够帮助到你！

**Comment by wushangwei** [comment]
好吧，看起来还是需要自己写HeaderRenderer，而不是复用自带的默认header了

**Comment by a1473838623** [comment]
here is my solution, add these to global.less
```less
.ant-pro-top-nav-header-base-menu {
  display: flex;
  margin-left: calc(10vw);
  align-items: center;
}

.ant-pro-top-nav-header-main-left {
  margin-left: calc(35vw);
}
```
