### ISSUE TITLE
🐛 [BUG] v6版本色弱模式会破坏布局

### ISSUE THREAD

**Issue by tnngo** [ant-design/ant-design-pro#10534]
### 🐛 bug 描述

v6版本，选择色弱模式时，表格会打穿布局。

### 📷 复现步骤 | Recurrence steps

在查询列表页面中，调整主题设置色弱模式，页面滚动到下方会看见列表贯穿了整体布局。

![image](https://user-images.githubusercontent.com/26067526/216881720-27a70930-02f9-4f33-90df-41e520d1ed6d.png)

### 💻 复现代码 | Recurrence code

仅官方v6版本demo，未写上任何代码

### © 版本信息

- Ant Design Pro 版本: 当前git clone后的最新版本，2023年02月06日 12点11分
- umi 版本：当前git clone后的最新版本，2023年02月06日 12点11分
- 浏览器环境：chrome，版本号：109.0.5414.119
- 开发环境：MAC OS

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🌟 问题分析

根据用户提供的信息，这是一个关于页面布局的问题，是由选择色弱模式导致表格打穿整体布局。考虑以下问题：

1. 表格的样式是否被正确设置了？
2. 是不是色弱模式的样式与表格样式冲突导致的？

### 🛠️ 解决方案

#### 1. 检查表格样式

首先检查表格的样式，是否正确设置了宽度、高度和 margin 属性。

```css
.table {
  width: 100%;
  height: 100%;
  margin: 0 auto;
  /* ...其他样式 */
}
```

#### 2. 检查色弱模式的样式

如果表格样式已经正确设置了，可以考虑检查色弱模式的样式是否与表格样式冲突。可以通过 Chrome 浏览器的开发者工具检查样式冲突。

另外，也可以尝试在 CSS 文件中改变或禁用颜色盲模式的样式：

```css
/* 禁用 */
.ant-color-blind-switch {
  display: none;
}

/* 修改样式 */
.ant-table-cell.ant-table-selection-column a.ant-checkbox-checked.ant-checkbox-disabled::after,
.ant-table-cell.ant-table-selection-column a.ant-checkbox-disabled::after,
.ant-table-cell.ant-table-selection-column .ant-checkbox-checked::after {
  background-color: #fff;
  border-color: #fff;
}
```

### 🔗 参考文档

- [Ant Design Pro 官方文档](https://beta-pro.ant.design/docs/getting-started-cn)
