### ISSUE TITLE
🧐[问题 | question] mix模式下，V6版本中的顶部和侧边菜单栏样式 怎样配置出V5的样式效果

### ISSUE THREAD

**Issue by JarnTang** [ant-design/ant-design-pro#10552]
### 🧐 问题描述 | Problem description
mix模式下，V6版本中的顶部和侧边菜单栏样式 怎样配置出V5的样式效果，期望结果如下图

### 🚑 其他信息 | Other information

<img width="572" alt="image" src="https://user-images.githubusercontent.com/791043/218623100-42981174-9eaa-4da9-ad20-d0536ec9b7ee.png">

OS:

Node：

浏览器 | browser：

**Comment by zhu-mingye** [comment]
同问

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，感谢您的提问。

首先，需要了解V6版本和V5版本的顶部和侧边菜单栏的样式区别。

V6版本的顶部和侧边菜单栏使用了全新的设计风格，与V5版本的样式不同。

如果您想要在V6版本中使用V5版本的样式，您可以考虑自己编写样式文件。

例如，可以在`src/assets/css`文件夹下创建一个命名为`v5-style.css`的样式文件，并在`main.js`中引入该文件。

然后，您可以根据V5版本的样式文件复制相关样式代码，并进行相应的修改。以下是一个简单的示例：

```css
/* v5-style.css */

// 顶部菜单栏
.app-header {
  background-color: #3f51b5;
  color: #fff;
}

// 侧边菜单栏
.layout-sidebar {
  background-color: #fff;
  color: #333;
}

// 左侧菜单项
.sidebar-menu li {
  margin-left: 0;
}

// 左侧菜单项悬浮效果
.sidebar-menu li:hover {
  background-color: #f5f5f5;
}
```

这些样式代码只是示例，您可以根据实际需要进行相应的修改。

最后，需要在`vue.config.js`文件中配置Webpack加载器，以将CSS文件打包到应用程序中：

```js
// vue.config.js
module.exports = {
  chainWebpack: (config) => {
    config.module
      .rule('css')
      .test(/\.css$/)
      .use('style-loader')
      .loader('style-loader')
      .end()
      .use('css-loader')
      .loader('css-loader')
      .end()
      .use('postcss-loader')
      .loader('postcss-loader')
      .options({
        plugins: [
          require('postcss-import')(),
          require('postcss-url')(),
          require('postcss-preset-env')({
            autoprefixer: {
              grid: true,
            },
          }),
        ],
      })
  }
}
```

建议您阅读Vue CLI官方文档，以了解更多有关Webpack加载器的信息：https://cli.vuejs.org/zh/guide/css.html#webpack-%E9%85%8D%E7%BD%AE
