### ISSUE TITLE
🧐[问题 | question] How to use consistent theming across Ant Pro and Ant?

### ISSUE THREAD

**Issue by zxti** [ant-design/ant-design-pro#10651]
Previously I learned that you can customize the color theme of a component (like ProLayout) using tokens ([issue](https://github.com/ant-design/ant-design-pro/issues/10618) - thanks @chenshuai2144!).

I see that pro-components has its own theming variable system. In addition to pro-components, I also use some ant components directly.

How should I ensure both of these match?

For example, if I just use some color tokens, plus a normal Ant `<Menu theme="dark">`, I get:

![image](https://user-images.githubusercontent.com/44424944/229193113-7b5fdb6a-610c-485d-abef-e3a5e34c7b30.png)

How do you keep them consistent? Is this easy or hard to do?

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


👋 [解决方案 | Solution]

To keep the theming consistent across Ant Pro and Ant, you can use the same variable system for both.

Ant Pro uses its own theming variable system, which is built on top of Less. For basic theming, you can use the `@primary-color` and other color related variables provided by Ant Pro, and they will work for both Ant Pro components and regular Ant components.

Here's an example of how you can customize the primary color:

```less
// customize primary color for Ant Pro and regular Ant components
// note that this should be included after the antd.less file

@import '~@ant-design/pro-layout/es/vars.less';

// override Ant Pro variables
@primary-color: #1890ff;

// override Ant variables
@menu-dark-bg: #001529;
@menu-dark-submenu-bg: #000c17;
```

For more advanced theming, such as modifying the styles of individual components, you can use the `theme.less` file provided by Ant Pro and extend it with your own variables.

Here's an example of how you can customize the styles of the `Menu` component:

```less
// customize menu item color for Ant Pro and regular Ant components
// note that this should be included after the antd.less file

@import '~@ant-design/pro-layout/es/vars.less';

// override Ant variables
@menu-dark-bg: #001529;
@menu-dark-submenu-bg: #000c17;

// Ant Pro variables
@pro-menu-item-active-bg: @primary-color;

// customize Ant components using Ant Pro variables
.ant-menu-dark .ant-menu-item-selected, .ant-menu-dark .ant-menu-item:active, .ant-menu-dark .ant-menu-item:hover {
  background-color: @pro-menu-item-active-bg;
}
```

For more information on customizing Ant Pro and Ant components with Less variables, see:

- [Customizing Theme](https://pro.ant.design/docs/theme-cn)
- [Theme Variables](https://ant.design/docs/react/customize-theme-cn#Less-%E5%8F%98%E9%87%8F)


I hope this helps! Let me know if you have any further questions.
