### ISSUE TITLE
🧐[问题 | question] 想知道这段less如何改写成ccs in js

### ISSUE THREAD

**Issue by joesdu** [ant-design/ant-design-pro#10659]
### 🧐 问题描述 | Problem description

想知道这段less如何改写成ccs in js

```less
.App-logo {
  height: 40vmin;
  pointer-events: none;
}

@media (prefers-reduced-motion: no-preference) {
  .App-logo {
    animation: App-logo-spin infinite 20s linear;
  }
}

.App-header {
  background-color: #282c34;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  color: white;
}

@keyframes App-logo-spin {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
```

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：
