### ISSUE TITLE
🧐[问题 | question]修改prolayout的菜单样式影响了页面中其他的Menu组件样式

### ISSUE THREAD

**Issue by Youmyin** [ant-design/ant-design-pro#10739]
### 🧐 问题描述 | Problem description
我想要修改菜单的样式，在app.tsx文件中的layout中做处理，一开始想通过配置token的方式，但是只有部分token样式生效，所以就改用覆盖样式来做，

app.tsx
```
import styles from './global.less'

export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
    return {
        className: styles.myStyle,
        ...
    }
}
```

global.less
```
.myStyle {
    :global {
        ...
        .ant-menu:not(.ant-menu-horizontal) .ant-menu-item-selected {
            color: #ffffff;
            background-color: #1890ff;
        }
    }
}
```
但是有个页面用了Menu组件，它继承了proLayout的菜单样式，但是Menu组件中不想要这些样式，所以想在Menu中覆盖样式，但是这个覆盖没有生效，请问怎样处理这个问题呀？
test.tsx
```
import styles from './styles.less'

const Test: () => {
  ...

  return (
    <Menu
        mode="inline"
        className={styles.MenuList}
    >
        {menuData.map((item: DictCategory, index: number) => {
            return (
                <Menu.Item
                    key={index}
                >
                    {item.name}
                </Menu.Item>
            );
        })}
    </Menu>
  )
}

export default Test
```

styles.less
```
.MenuList {
    :global {
        .ant-menu:not(.ant-menu-horizontal) .ant-menu-item-selected {
            color: #1890ff;
            background-color: #ffffff;
        }
    }
}
```
OS:windows 10

Node：18.13.0

浏览器 | browser：chrome

@ant-design/pro-components：2.4.15

antd：4.23.3

antd pro：V5

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


## 问题解决方案

在 ProLayout 中修改菜单样式影响到了页面中其他的 Menu 组件样式，希望在 Menu 组件中覆盖样式但是没有生效。可以尝试以下解决方案：

1. 使用 CSS Modules 解决样式冲突。在 `styles.less` 中的 `.MenuList` 类名前添加 `:local`，并在 `Test` 组件中引入样式时使用 `styles.MenuList`。这样可以确保样式只在当前作用域生效。

```less
:local {
  .MenuList {
    .ant-menu:not(.ant-menu-horizontal) .ant-menu-item-selected {
      color: #1890ff;
      background-color: #ffffff;
    }
  }
}
```

```tsx
import styles from './styles.less';

const Test: React.FC = () => {
  return (
    <Menu mode="inline" className={styles.MenuList}>
      {/* ... */}
    </Menu>
  );
};

export default Test;
```

2. 使用 CSS 选择器的权重来覆盖样式。在 `styles.less` 中的选择器前加上更高的权重，比如使用父选择器。

```less
.myStyle .MenuList {
  .ant-menu:not(.ant-menu-horizontal) .ant-menu-item-selected {
    color: #1890ff;
    background-color: #ffffff;
  }
}
```

```tsx
import styles from './styles.less';

const Test: React.FC = () => {
  return (
    <div className={styles.MenuList}>
      <Menu mode="inline">
        {/* ... */}
      </Menu>
    </div>
  );
};

export default Test;
```

3. 使用 CSS Modules 解决样式冲突，并在 `Test` 组件中使用 `:global` 声明全局样式。

```less
:global {
  .MenuList {
    .ant-menu:not(.ant-menu-horizontal) .ant-menu-item-selected {
      color: #1890ff;
      background-color: #ffffff;
    }
  }
}
```

```tsx
import styles from './styles.less';

const Test: React.FC = () => {
  return (
    <Menu mode="inline" className={styles.MenuList}>
      {/* ... */}
    </Menu>
  );
};

export default Test;
```

以上是几种常见的解决方案，根据具体情况选择合适的方法来解决样式冲突问题。
