### ISSUE TITLE
左侧菜单栏滚动条样式问题！！！🧐[问题 | question]

### ISSUE THREAD

**Issue by zhangyuanlin666** [ant-design/ant-design-pro#10757]
### 🧐 问题描述 | Problem description

ant design pro comlete版本左侧菜单栏滚动条比较漂亮， simple版本却挺丑的，修改那个地方

### 🚑 其他信息 | Other information

OS:

Node：

浏览器 | browser：

**Comment by zhangyuanlin666** [comment]
![image](https://github.com/ant-design/ant-design-pro/assets/66874263/e92fb4eb-b589-4ea2-aa39-5ac94b252895)

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


问题的解决方案可能有以下几种方式：

1. 使用 CSS 自定义滚动条样式：

   可以使用 CSS 的 `::-webkit-scrollbar` 伪类来自定义滚动条样式。例如，可以修改滚动条的颜色、宽度和边框等属性，使其更符合设计要求。

   ```css
   ::-webkit-scrollbar {
     width: 8px;
     background-color: #f5f5f5;
   }
   ::-webkit-scrollbar-thumb {
     background-color: #888;
   }
   ::-webkit-scrollbar-thumb:hover {
     background-color: #555;
   }
   ```

   这样就可以修改滚动条的样式了。你可以根据具体的需求来修改滚动条的颜色、宽度等属性。

2. 使用第三方库定制滚动条样式：

   如果对 CSS 自定义滚动条样式不够满意，也可以考虑使用第三方库来定制滚动条样式。例如，`react-custom-scrollbars` 是一个能够提供自定义滚动条样式的 React 组件。你可以使用它来替代默认的滚动条，从而实现更好看的滚动条效果。

   ```jsx
   import { Scrollbars } from 'react-custom-scrollbars';

   // 使用 Scrollbars 组件替代原生的滚动条
   <Scrollbars style={{ width: 200, height: 300 }}>
     {/* 这里放置需要滚动的内容 */}
   </Scrollbars>
   ```

   通过使用 `Scrollbars` 组件，你可以通过自定义 CSS 来修改滚动条的样式，例如颜色、宽度和边框等。

3. 借助 Umi 和 Ant Design Pro 进行定制化开发：

   如果你正在使用 Ant Design Pro，可以通过 Umi 和 Ant Design Pro 提供的配置项来进行定制化开发。具体来说，可以通过修改 `config/config.js` 中的配置，来调整左侧菜单栏的滚动条样式。

   ```javascript
   export default {
     // 一些其他的配置项
     // ...

     // 修改左侧菜单栏的滚动条样式
     theme: {
       'menu-dark-color': '#333',
       'menu-dark-bg': '#f5f5f5',
       // 其他相关的样式配置
       // ...
     },
   };
   ```

   通过修改 `theme` 配置项中的相关样式，你可以实现定制化的滚动条样式。

以上是几种可能的解决方案，你可以根据具体的需求和技术栈来选择适合的方案。希望能对你有所帮助！🙂
