### ISSUE TITLE
🧐[问题 | question] antd v6(umi4) 左侧菜单的滚动条的样式如何修改？

### ISSUE THREAD

**Issue by mendellin** [ant-design/ant-design-pro#10799]
### 🧐 问题描述 | Problem description

 最新版ant v6 (umi 4)，左侧菜单的滚动条的样式很粗，不好看，如何修改这个菜单滚动条的样子呢？谢谢

### 🚑 其他信息 | Other information

![image](https://github.com/ant-design/ant-design-pro/assets/5884945/50e36854-5467-464a-9535-ac054cb2f4c8)

OS:

Node：

浏览器 | browser：

**Comment by chenshuai2144** [comment]
> 值得注意是的百分之二十的问题都可以用重装依赖来解决，所以你可以尝试一下：
删除 'node_modules' 文件夹 -> 删除 'package-lock.json'或 'pnpm-lock.yaml' 文件 -> 运行 'pnpm install' 或  'npm install' 命令


antd v6（umi4）中，左侧菜单的滚动条样式可以通过以下步骤进行修改：

1. 在你的项目目录下，找到 `src` 文件夹，然后找到 `global.less` 文件（如果没有该文件，可以自己创建一个）。

2. 打开 `global.less` 文件，添加以下代码来修改滚动条的样式：

```less
@import '~antd/dist/antd.less';

.rc-drawer-content-wrapper {
  ::-webkit-scrollbar {
    width: 6px;
    height: 0;
    background-color: #fff;
  }

  ::-webkit-scrollbar-thumb {
    background-color: #000;
    border-radius: 3px;
  }
}
```

3. 保存文件并重新启动项目，你会发现左侧菜单的滚动条样式已经修改了。

这里使用了 `less` 来编写样式，并使用了 Ant Design 的内置样式变量。通过修改 `.rc-drawer-content-wrapper` 下的 `::-webkit-scrollbar` 和 `::-webkit-scrollbar-thumb` 样式，可以分别控制滚动条的外观和滑块的样式。

注意：在修改样式之前，确保已经引入了 Ant Design 的样式文件，并且重新启动项目以使修改生效。此外，如果你的项目中使用了自定义主题，可能需要根据实际情况调整样式。
