### ISSUE TITLE
🧐[问题 | question] 怎么设置 自定义 header 的border-block-end

### ISSUE THREAD

**Issue by xiohuchi** [ant-design/ant-design-pro#11203]
### 🧐 问题描述 | Problem description
```js
export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
  return {
    headerRender: () => {
      return <Header />;
    },
    .......
}
```

问题：内容和自定义header中间有一条横线，发现是layout-header.ant-pro-layout-header有个样式，
> border-block-end ： 1px solid rgba(5, 5, 5, 0.06)

怎么去除横线????

### 版本
2024年4月7日最新版

**Comment by xiohuchi** [comment]
已经解决了，global.less添加全局样式可以了
```css
.ant-pro-layout .ant-layout-header.ant-pro-layout-header-fixed-header {
  border-block-end: 0 solid rgba(5, 5, 5, 0.06);
}
```
