### ISSUE TITLE
🧐[问题 | question] Unable to set full height of an element of ant-pro-layout-content

### ISSUE THREAD

**Issue by ngminhthanh12a3** [ant-design/ant-design-pro#11412]
### 🧐 问题描述 | Problem description

Unable to set the full height of an element of ant-pro-layout-content.

I'm trying to set the full height of an element inside the ant-pro-layout-content. But it doesn't work.

My additional content of the `global.less` to set the full height of the ant-pro-layout-content.

```css
.ant-layout {
  .ant-pro-layout-container {
    .ant-pro-layout-content {
      min-height: 100vh;
    }
  }
}
```

The results are as follows:

![Untitled](https://github.com/user-attachments/assets/4f37cf5c-4d4a-4bda-96b9-6b2002c4315e)
![image](https://github.com/user-attachments/assets/95d31859-c3b4-4a38-8b79-87fbb984cd1d)

### 🚑 其他信息 | Other information

OS: Ubuntu 22.04

Node：20.17.0

浏览器 | browser：Microsoft Edge
