### ISSUE TITLE
全局覆盖组件样式不生效

### ISSUE THREAD

**Issue by huangzhuolin** [ant-design/ant-design-pro#1992]
想要改动全局的antd组件样式，例如想将Table中原来的`border-radius: 4px 4px 0 0`改为`border-radius: 0`
按照文档的说法，新建一个`overwrite.less`文件，里面加上
```less
:global {
  .ant-table {
    table {
      border-radius: 0;
    }
  }
}
```
并在`index.js`中引入。

虽然声明了`:global`，自定义的样式并未生效，而是被原来的样式覆盖掉了，如图：
<img width="534" alt="ant-table" src="https://user-images.githubusercontent.com/8508155/44033506-2a1a75e8-9f3d-11e8-967e-e51d9411b479.png">

这种方法是否可行？
