### ISSUE TITLE
antd Pro的iconfont图标无法引用，且Pro的业务图标文档需要更新的问题

### ISSUE THREAD

**Issue by renyi818** [ant-design/ant-design-pro#207]
链接地址：https://pro.ant.design/docs/biz-icon-cn
该文档描述的方式是使用css文件，然后封装成BizIcon的方式去使用。实际上现在的pro使用的less，在使用方式上不同，尤其
`const BizIcon = (props) => {`
`  const { type } = props;`
` return <i className={`iconfont icon-${type}`} />;`
`};`
中的**return <i className={`iconfont icon-${type}`} />** 方式已经不再适用。
最好能更新新的用法，谢谢

之所以提这个，是因为不管用css，还是less，甚至改造成classNames去使用，都没办法使iconfont上的图标显示出来，特来求助

**Comment by afc163** [comment]
> 都没办法使iconfont上的图标显示出来

你最好描述具体的问题，你是怎么做的？有没有可重现的代码？

**Comment by renyi818** [comment]
几次更新已将之前的这部分代码删掉了。
大概描述下：
首先在iconfont.cn上添加图标到项目，生成对应的css文件，我将文件中的代码拷贝出来，保存为BizIcon.css
[BizIcon.css.zip](https://github.com/ant-design/ant-design-pro/files/1497870/BizIcon.css.zip)

1.采用文档的css方式。
在components文件夹下新建了一个BizIcon文件夹且同时新建了一个index.js， 然后在替换了BasicLayout.js里的<icon>标签，发现没有起作用，随之改写BizIcon.js，写死type类型，如下：
const BizIcon = (props) => {
//const { type } = props;
return <i className={iconfont icon-xitong} />; //这里将type类型固定为css文件里的type
};
还是没有显示

2.将前面的BizIcon.css改为less文件
改写index.js，
[index.js.zip](https://github.com/ant-design/ant-design-pro/files/1497877/index.js.zip)

如下图：
![default](https://user-images.githubusercontent.com/30144443/33156513-5b145a88-d035-11e7-8ca5-6f453de94ed9.png)


再次替换了BasicLayout.js里的<icon>标签，发现还是没有出现图标。


你好，这是我的处理方式，不过我想，如果能更新Pro文档里的描述，以现有架构的结构来描述下如何实现的可行思路，是否更清晰一点？

**Comment by afc163** [comment]
`styles.xx-xx` 是 JavaScript 语法错误。

**Comment by nikogu** [comment]
@renyi818 切换写法后是否解决问题

**Comment by renyi818** [comment]
抱歉，最近在忙项目上的事情，还没试，我今天试试 ：）

**Comment by renyi818** [comment]
确实是可以的， 
 const classString = classNames(styles.iconfont,styles['icon-'+type]);
这么写就可以了，谢谢！

**Comment by renyi818** [comment]
@afc163 @nikogu 另外还发现一个问题，如果使用自定义图标，会出现收缩左侧菜单，文字没有隐藏的问题。如下图
![default](https://user-images.githubusercontent.com/30144443/33539682-a8902b4a-d902-11e7-87b9-3b6692c9e6e7.png)
测试了下，使用原Icon标签就正常， 一旦使用自定义图标标签，就会出现。 出现的效果等同于，将icon从页面上去掉的效果一样。

**Comment by xiaosongxiaosong** [comment]
`src/index.less` 文件中为 `iconfont` 增加一下在 `ant-menu-inline` 中的样式 @renyi818 
```less
./src/index.less
:global(.ant-menu-inline) {
  border-right: 0 none;
}

 :global(.ant-menu-item) :global(.iconfont) {
  min-width: 14px;
  margin-right: 10px;
}

 :global(.ant-menu-inline-collapsed)> :global(.ant-menu-item) :global(.iconfont)+span {
  max-width: 0;
  display: inline-block;
  opacity: 0;
}

:global(.ant-menu-inline-collapsed-tooltip) :global(.iconfont) {
  display: none;
}
```
