### ISSUE TITLE
DescriptionList组件样式问题

### ISSUE THREAD

**Issue by Tan90Qian** [ant-design/ant-design-pro#2172]
在`src/components/DescriptionList/index.less`文件中有
```less
.term {
  // Line-height is 22px IE dom height will calculate error
  line-height: 20px;
  // ...
}
.detail {
  line-height: 22px;
  // ...
}
```
这样的一句注释，说22px的行高在IE下会产生错误，但是仅修改了term的行高，detail的行高却没设置，因此当服务端回传的详情数据正好为空时，该项Description的高度会因为detail的塌陷而减少2px造成布局错乱，个人觉得应该对detail也设置line-height为20px或者设置min-height为20px保证布局；
而当服务端回传的详情数据中部分超过1行内容，部分不超过时，也可能造成布局错乱，此处感觉可以`Ellipsis `配合，给DescriptionList组件新增一个line属性保证同样行数的显示效果
