### ISSUE TITLE
fixed header时高级表单页面的bug

### ISSUE THREAD

**Issue by ilaipi** [ant-design/ant-design-pro#2329]
就是底部的 Copyright 看不到了，问题也不是很大，但是看起来有点难受。

![image](https://user-images.githubusercontent.com/1689135/45666172-1ee20080-bb47-11e8-9144-2f1fbc3c7339.png)

**Comment by chenshuai2144** [comment]
设计如此！

**Comment by kennylbj** [comment]
AdvancedForm css里有这么一段：
```css
// custom footer for fixed footer toolbar
.advancedForm + div {
  padding-bottom: 64px;
}
```
本意是为了解决这个问题的。

但是观察页面最终的页面元素，大概为
```html
<div class='ant-layout-content'>
  <div class='advancedForm'>
    ......
  </div>
</div>
<div class='ant-layout-footer'>
  ......
</div>
```
这里的`advancedForm + div ` 选择不到 `ant-layout-footer`，因此上述css无法生效。

最直接的办法是在ant-layout-content上做选择器，但是css无法选择parent。

还有什么其他思路吗？
