### ISSUE TITLE
开关侧边菜单时Header右边部分的元素出现跳动现象

### ISSUE THREAD

**Issue by shend** [ant-design/ant-design-pro#2452]
在固定 Header 和固定侧边菜单的模式下，开关侧边菜单会导致 Header 右边部分的页面元素出现跳动现象。

官网预览链接如下：
https://preview.pro.ant.design/dashboard/analysis?fixedHeader=1&fixSiderbar=1

问题可能是下面这行过渡动画导致的，我把这一行注释掉就不会再出现跳动现象。
https://github.com/ant-design/ant-design-pro/blob/01fc86deb6abf6312aa21647ad78f5f7f239b56e/src/layouts/Header.less#L6

**Comment by shend** [comment]
加一行`right: 0;`可以解决这个问题：

```less
.fixedHeader {
  position: fixed;
  top: 0;
  right: 0;
  width: 100%;
  z-index: 9;
  transition: width 0.2s;
}
```
