### ISSUE TITLE
How to extend an ant design class with css-modules and less(sass)

### ISSUE THREAD

**Issue by xgenvn** [ant-design/ant-design-pro#285]
Hi,

I've searched around for this but can't find any good result.
Sometimes I need to create a new class that extending a predefined style from antd, eg:
```less
.crazy_container{
    .crazy_btn{
        &:extend(.ant-btn .ant-btn-primary all);
        padding: 30px;
    }
}
```
```html
<Button className={style.crazy_btn}></Button>
```

But this seems not having effect.

Can you add a documentation about this (especially on LESS and css-module)? A short guideline is also good.
1. How to create a class that extend ant based style?
2. How to use css-modules with LESS for ant style extending?

Thank you.

**Comment by WhatAKitty** [comment]
1.
```less
@import "~antd/lib/style/themes/default.less";

span {
  font-size: @font-size-base;
  line-height: 22px;
}
```

2.
```
import styles from '.../xxx.less'

<p className={styles.xxx}></p>
```
