### ISSUE TITLE
build 后 css 没有压缩

### ISSUE THREAD

**Issue by guihua** [ant-design/ant-design-pro#313]
执行 build 构建时，css 文件没有压缩
```css
/*!
 * 
 * ant-design-pro v0.2.3-rc.3
 * 
 * Copyright 2015-present, Alipay, Inc.
 * All rights reserved.
 *       
 */
/* stylelint-disable at-rule-empty-line-before,at-rule-name-space-after,at-rule-no-unknown */
/* stylelint-disable declaration-bang-space-before */
/* stylelint-disable declaration-bang-space-before */
.antd-pro-charts--chart-card-chartCard {
  position: relative;
}
.antd-pro-charts--chart-card-chartCard .antd-pro-charts--chart-card-meta {
  color: rgba(0, 0, 0, 0.45);
  font-size: 14px;
  position: relative;
  line-height: 22px;
  height: 22px;
}
.antd-pro-charts--chart-card-chartCard .antd-pro-charts--chart-card-action {
  cursor: pointer;
  position: absolute;
  top: 0;
  right: 0;
}
...
```
