### ISSUE TITLE
InputNumber 怎么不显示右侧的步距？

### ISSUE THREAD

**Issue by zhouguanglong** [ant-design/ant-design-pro#3383]
不想让 InputNumber 显示右侧步距样式，该怎么做呢？

**Comment by imhele** [comment]
覆盖掉 `.ant-input-number-handler-wrap` 的样式，比如
```less
:global(.ant-input-number-handler-wrap) {
  display: none;
}
```
