### ISSUE TITLE
npm run docker:dev can't request to localhost

### ISSUE THREAD

**Issue by tranducit95** [ant-design/ant-design-pro#4043]
I use Laravel as backend, laradock initializes the docker environment.
Run npm run docker: dev (`use proxy and run start: no-mock`) error:

 `[HPM] Error occurred trying to proxy request / api / auth / login from localhost: 8000 to http: //localhost / (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors).`
note: `localhost`: server backend using laravel 

I don't know what the error is and how to fix it.
If you don't use docker and run `npm run start: no-mock` everything back to normal, I'm thinking that there is a problem with the network between containers, I'm not good, please help me

**Comment by aarabmed** [comment]
my situation is quite like your , i have 2 containers one for Ant design pro and the other for a local api , when i try to do request from the api container it says : 
`[HPM] Error occurred while trying to proxy request /users localhost:7000 to http://localhost:8080 (ECONNRESET)` 
ps : i have already set the proxy in the config file of ant design pro  as bellow 
   proxy: {
     '/api': {
       target: 'http://localhost:8080/',
       changeOrigin: true,
       pathRewrite: { '^/api': '' },
        },
  },
i'm wondering is there another configuration need to be made to make the proxy works between container, 
if i use ant design pro with bash instead of docker, everything work great :/ :/

**Comment by bartimaeus** [comment]
@tranducit95 do you have a copy of your docker-compose.yml?

**Comment by tranducit95** [comment]
I'm use default docker-composer laradock and ant design pro.

**Comment by bartimaeus** [comment]
I think you'll want to modify your ant design pro docker-compose.dev.yml to  link the laravel container

**Before**
```
version: "3.5"

services:
  ant-design-pro_dev:
    ports:
      - 8000:8000
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: "ant-design-pro_dev"
    volumes:
      - ../src:/usr/src/app/src
      - ../config:/usr/src/app/config
      - ../mock:/usr/src/app/mock
```

**After**
```
version: "3.5"

services:
  ant-design-pro_dev:
    ports:
      - 8000:8000
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: "ant-design-pro_dev"
    external_links:
      - [laravel_container_name]:laravel
    volumes:
      - ../src:/usr/src/app/src
      - ../config:/usr/src/app/config
      - ../mock:/usr/src/app/mock
```

After you have linked the laravel container then you can update and design's api to hit `http://laravel:8000`.

[external_links](https://docs.docker.com/compose/compose-file/#external_links) is a way to link already running containers.

The default docker-compose in ant-design-pro only connects the nginx and the ant-design-pro containers.
