### ISSUE TITLE
Scrollbar is not appearing in sidebar menu, when the menu contains more items ,

### ISSUE THREAD

**Issue by THARAKS** [ant-design/ant-design-pro#4208]
When you have more menu items or routes in side bar , the scroll bar is not appearing, and you have to scroll whole page to select any menu items
![menu itens](https://user-images.githubusercontent.com/15693408/57836938-66f11a00-77df-11e9-80e8-b017f354fbb7.png)
![menu2](https://user-images.githubusercontent.com/15693408/57836946-6b1d3780-77df-11e9-9267-5041d15319a6.png)

**Comment by chenshuai2144** [comment]
This problem exists in older versions. You can give
```css
.ant-layout-sider-children{
     heigth:100%;
    overflow: auto;
}
```
