### ISSUE TITLE
docker-compose 部署pro + nginx 无法自动compile

### ISSUE THREAD

**Issue by wangweikang** [ant-design/ant-design-pro#4559]
```
nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html/static:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    links:
      - ui

  ui:
   image: node:10
   restart: always
   working_dir: "/opt/app"
   ports:
     - "18001:8000"
   volumes:
     - ./frontend-ui:/opt/app:rw
   command: sh -c "test -d node_modules && npm start || (npm install && npm start)"
```
