### ISSUE TITLE
关于 stylelint 和 css 属性的2个问题(TS版本)

### ISSUE THREAD

**Issue by ykst615** [ant-design/ant-design-pro#4901]
1. 在less中使用其他字体, stylelint 如何配置? 求教如何去找到配置内容(jslint也是这样),
引入内容如下图:
```javascript
const fabric = require('@umijs/fabric');

module.exports = {
  ...fabric.stylelint,
};
```

2. 在less 文件中写入如下css, 当时无妨编译到项目中
```css
.class {
  display: -webkit-box;
  // other
  -webkit-line-clamp: 2;
  // 下面这行在浏览器中找不到
  -webkit-box-orient: vertical;
}

```
