### ISSUE TITLE
topmenu模式下，如何设置页面宽度1200px

### ISSUE THREAD

**Issue by manyhelp** [ant-design/ant-design-pro#5167]
topmenu模式下，如何设置页面宽度1200px？
目前是全屏覆盖的，想固定宽度1200px，中间显示。

**Comment by xiaohuoni** [comment]
是这个意思吗？
```css
#root {
    width: 1200px;
    margin: auto;
}
```
