### ISSUE TITLE
🐛[BUG] LoginForm验证时的提示信息导致表单和按钮移动

### ISSUE THREAD

**Issue by TianEnPang** [ant-design/ant-design-pro#5960]
### 🐛 bug 描述

- Login中的LoginForm验证时的错误提示信息导致表单和按钮移动

### 📷 复现步骤

- 使用 `yarn create umi` 创建antd@4的项目即可发现 

### 🏞 期望结果

- 已找到原因代码
  目录：src/pages/user/login/components/Login/index.less:11~13

  ```css
    .ant-form-item {
      margin: 0 2px 24px;
    }
  ```

### 💻 复现代码

- 使用 `yarn create umi` 创建antd@4的项目即可发现 

### © 版本信息

- Ant Design Pro 版本:  4.0.0
- antd 版本: 4.0.0-rc.4

### 🚑 其他信息
![demo](https://user-images.githubusercontent.com/32772271/74175812-7f5c6b00-4c71-11ea-9339-62e2a984235f.gif)
