### ISSUE TITLE
👑 [需求]希望BasicLayout 提供resize参数，让开发者自行选择是否开启rc-resize-observer

### ISSUE THREAD

**Issue by exvu** [ant-design/ant-design-pro#5988]
### 🥰 需求描述

现在有一个业务需要让content页面占满剩余全部空间，由于BasicLayout 使用rc-resize-observer导致出现min-height:1000px,导致content页面不能占满剩余全部空间
<main class="ant-layout-content" style="min-height:1000px">
### 🧐 解决方案

1.给content元素设置样式max-height:calc(100vh-60px[header的高度])，此方法不是很优美
2.设置ant-layout-content样式
```css
.ant-layout-content{
 min-height: 0 !important;
}
```css
```

### 🚑 建议
希望BasicLayout 提供resize参数，让开发者自行选择是否开启rc-resize-observer
