### ISSUE TITLE
以独立的方式使用antd-pro，出现样式错乱的问题。

### ISSUE THREAD

**Issue by lyingd** [ant-design/ant-design-pro#679]
如图：
![](https://github.com/lyingd/antd-pro-standalone/blob/master/styleerror.png?raw=true)

demo：
[antd-pro-standalone](https://github.com/lyingd/antd-pro-standalone.git)

**Comment by afc163** [comment]
不在 https://pro.ant.design/components/AvatarList-cn 列表里的组件是无法使用的。

@ddcat1115 @nikogu @chenshuai2144 需要把没提供文档的组件从 ant-design-pro npm 包里移除掉。

**Comment by lyingd** [comment]
好的，没注意到GlobalHeader没在文档提供

**Comment by chenshuai2144** [comment]
GlobalHeader  不复杂 要不要独立出来

**Comment by lyingd** [comment]
我把GlobalHeader单独提出来使用，header样式按文档方法无法覆盖组件原有样式
无效：
```css
.header {
   :global {
    .ant-layout-header {
      padding: 0 12px 0 0;
      background: #fff;
      box-shadow: 0 1px 4px rgba(0, 21, 41, .08);
      position: relative;
    }
  }
}
```
但可以按这样子覆盖：
```css
.header {
  padding: 0 12px 0 0 !important;
  background: #fff !important;
  box-shadow: 0 1px 4px rgba(0, 21, 41, .08) !important;
  position: relative !important;
}
```
其最终生成的html如下，是否可以考虑antd原有样式放在前边？
```html
<div css="header___1L3tU ant-layout-header"></div>
```
