### ISSUE TITLE
🧐[问题] 导航栏中的menu 与 submenu之间的间距怎么调整呢？

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design-pro#7436]
### 🧐 问题描述

导航栏中的menu 与 submenu之间的间距怎么调整呢？

### 🚑 其他信息

如下图所示，感觉好难调，https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less 这个里面也没有找到相关配置

![QQ图片20201010162613](https://user-images.githubusercontent.com/23411433/95650301-66180100-0b15-11eb-9787-3d8ce6354e7a.png)

**Comment by xrkffgg** [comment]
真想修改也有办法。
当前 SubMenu 渲染 html 后的 id 是 SubMenu 的 key 加 $Menu

你可以给这个 id 加 css

```css
#SubMenu$Menu {
    margin-top: 10px;
}
```

**Comment by xrkffgg** [comment]
带上 class  更好一些

```css
#SubMenu$Menu .ant-menu-sub {
    margin-top: 10px;
}
```
