### ISSUE TITLE
🐛[BUG] 文档描述Bug，修改样式章节

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#7728]
### 🐛 bug 描述

文档描述Bug，修改样式章节。 主要是:global不能用
https://pro.ant.design/docs/style-cn

### 📷 复现步骤

* 下载代码
* 按照文档welcome.less中添加
```less
.customSelect {
  :global {
    .ant-btn {
      background-color: red;
    }
  }
}
```
* 在welcome.tsx中添加
```tsx
<Button className={styles.customSelect}>dddd</Button>
```
* 没有看到效果。

### 🏞 期望结果

文档写复杂了，没有必要使用:global来定义。
* 如果要想全局覆盖ant的标签，就在global.less中定义就行。

```less
.ant-btn {
  background-color: red;
}
```

* 如果在页面中覆盖，就写一个类就行了，好像不需要` :global {`这么复杂的定义了
```less
.customSelect {
      background-color: red;
}
```
