### ISSUE TITLE
🧐[问题]npm run precommit 报错

### ISSUE THREAD

**Issue by Songkunda** [ant-design/ant-design-pro#7884]
### 🧐 问题描述

```bash
npm run precommit

> ant-design-pro@5.0.0-beta.2 precommit
> lint-staged

⚠ Skipping backup because there’s no initial commit yet.

✔ Preparing...
✔ Hiding unstaged changes to partially staged files...
⚠ Running tasks...
  ❯ stylelint --syntax less [FAILED]
    ✖ stylelint --syntax less [FAILED]
  ✔ Running tasks for **/*.{js,jsx,ts,tsx}
  ✔ Running tasks for **/*.{js,jsx,tsx,ts,less,md,json}
✔ Applying modifications...
↓ Skipped because of errors from tasks. [SKIPPED]

✖ stylelint --syntax less:

src/components/Footer/index.less
  9:5  ✖  Expected "right" to come before "background" in group "Positioning"      order/properties-order
 11:5  ✖  Expected "bottom" to come before "left" in group "Positioning"           order/properties-order

```

### 💻 示例代码

```less
@import '~antd/es/style/themes/default.less';

.footer {
  height: 20vh;
  text-align: center;
  a {
    position: absolute;
    background: url('/ft_bg.png');
    right: 0;
    left: 0;
    bottom: 0;
    color: white;
    line-height: 44px;
  }
}

```

### 🚑 其他信息

* 即使更改为要求的正确顺序 在运行npm run precommit 还是会报错,他在运行stylelint --syntax les之前格式化了less文件导致顺序不正确而报错,怀疑是prettier --write将文件格式化错误
* stylelint --fix "src/**/*.less" 可以修复为正确顺序 但依然不能通过precommit
