### ISSUE TITLE
🧐[问题]  如何覆盖antDesign的样式？

### ISSUE THREAD

**Issue by fanhualei** [ant-design/ant-design-pro#7954]
### 🧐 问题描述

如何覆盖antDesign的样式？

例如：PageContainer 这个组件里面有一个样式是：`ant-page-header-footer`

我想将`ant-page-header-footer` 修改成下面的，怎么做呢？
```less
    .ant-page-header-footer {
      margin-top: 160px;
    }
```

> 这是我页面的代码

我想在`customSelect` 自定义的样式中，将`ant-page-header-footer` 给覆盖了

```tsx
import React from 'react';
import { PageContainer } from '@ant-design/pro-layout';
import { Card } from 'antd';
import styles from './index.less';

export default () => {
  return (
    <PageContainer
      breadcrumb={undefined}
      title={undefined}
      className={styles.customSelect}
      tabList={[
        {
          tab: '基本信息',
          key: 'base',
        },
        {
          tab: '详细信息',
          key: 'info',
        },
      ]}
    >
      <Card title="权限管理123" style={{ marginBottom: 15 }} key="QueryTable">
        <br />
        kkkkkkkkkkkkkkkkkkk
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
      </Card>
    </PageContainer>
  );
};
```

**Comment by fanhualei** [comment]
我不想将下面的样式放入到global.less中，来覆盖全局的样式。

```less
.ant-page-header-footer {
  margin-top: 160px;
}
```
