### ISSUE TITLE
🧐[问题]请问怎么改变 PageContainer 中 Tabs 的样式？

### ISSUE THREAD

**Issue by FrankSFLYS** [ant-design/ant-design-pro#9408]
### 🧐 问题描述

使用了 PageContainer 中的 Tabs，示例代码见下。效果如图。现在的问题是激活的页签是白色的，未激活是灰色，我想把它变成激活时是灰色（与 `@layout-body-background` 一致），未激活是白色，请问该怎么改呢？
![image](https://user-images.githubusercontent.com/10843159/145762743-99d8cf32-cc2e-4894-b931-b476da4fc328.png)

### 💻 示例代码

这是 PageContainer：
```ts
<PageContainer
      tabList={libTabs}
      tabActiveKey={activeKey}
      tabProps={{
        type: 'editable-card',
        hideAdd: true,
        onChange: (k) => {
          setActiveKey(k);
        },
        ...tabProps,
      }}
/>
...
</PageContainer>
```

在 Ant Design 的标签页 Tabs 中找到了一部分 css，但是在 Tabs 中试了不管用，代码如下。其中，对 `div` 背景色的改变生效了，说明引入应该没问题，但是所有对 tab 的修改全都没生效，包括我把所有颜色都改成红色，没有一个地方变化的。
```ts
<div className={styles['card-container']}>
        <Tabs type="card">
          <TabPane tab="Tab Title 1" key="1">
            <p>Content of Tab Pane 1</p>
            <p>Content of Tab Pane 1</p>
            <p>Content of Tab Pane 1</p>
          </TabPane>
          <TabPane tab="Tab Title 2" key="2">
            <p>Content of Tab Pane 2</p>
            <p>Content of Tab Pane 2</p>
            <p>Content of Tab Pane 2</p>
          </TabPane>
          <TabPane tab="Tab Title 3" key="3">
            <p>Content of Tab Pane 3</p>
            <p>Content of Tab Pane 3</p>
            <p>Content of Tab Pane 3</p>
          </TabPane>
        </Tabs>
      </div>
```
```less

.card-container div {
  background-color: yellowgreen;
}

.card-container p {
  margin: 0;
}

.card-container > .ant-tabs-card .ant-tabs-content {
  height: 520px;
  margin-top: 50px;
}
.card-container > .ant-tabs-card .ant-tabs-content > .ant-tabs-tabpane {
  padding: 216px;
  background: red;
}
.card-container > .ant-tabs-card > .ant-tabs-nav::before {
  display: none;
}
.card-container > .ant-tabs-card .ant-tabs-tab,
[data-theme='compact'] .card-container > .ant-tabs-card .ant-tabs-tab {
  color: red;
  background: red;
  border-color: red;
}
.card-container > .ant-tabs-card .ant-tabs-tab-active,
[data-theme='compact'] .card-container > .ant-tabs-card .ant-tabs-tab-active {
  color: @primary-color;
  background: red;
  border-color: red;
}
#components-tabs-demo-card-top .code-box-demo {
  padding: 24px;
  overflow: hidden;
  background: #f5f5f5;
}
[data-theme='compact'] .card-container > .ant-tabs-card .ant-tabs-content {
  height: 120px;
  margin-top: -8px;
}
[data-theme='dark'] .card-container > .ant-tabs-card .ant-tabs-tab {
  background: red;
  border-color: red;
}
[data-theme='dark'] #components-tabs-demo-card-top .code-box-demo {
  background: #000;
}
[data-theme='dark'] .card-container > .ant-tabs-card .ant-tabs-content > .ant-tabs-tabpane {
  background: #141414;
}
[data-theme='dark'] .card-container > .ant-tabs-card .ant-tabs-tab-active {
  background: #141414;
  border-color: #141414;
}

```

### 🚑 其他信息

上述 Tabs 的效果如图：
![image](https://user-images.githubusercontent.com/10843159/145763185-eaaf83e1-5ded-450a-b293-2b702a656bcf.png)
