### ISSUE TITLE
🧐[Question] - Layout error after login redirect

### ISSUE THREAD

**Issue by renanwilliam** [ant-design/ant-design-pro#9878]
### 🧐 Problem description

After a login redirect using history push, the next screen is without layout and all design messed. After a refresh, everything works.

Login page:
<img width="2020" alt="image" src="https://user-images.githubusercontent.com/19995615/170562099-d8b07dba-21ad-474b-9fbd-031eb1c58da4.png">

Next page after `history.push`:
<img width="2020" alt="image" src="https://user-images.githubusercontent.com/19995615/170562198-8be15e13-43b7-4725-8454-83f91c0abe4f.png">

Same page after a refresh (F5):
<img width="2020" alt="image" src="https://user-images.githubusercontent.com/19995615/170562245-9e2e783a-4b78-40c2-bc3e-d9ea9c4167f6.png">

### 💻 Sample code

At login page:
```typescript
          const userInfo = await queryCurrent();
          await setInitialState((s) => ({
            ...s,
            currentUser: userInfo,
          }));
          //replaceGoto();

          if (!history) return;
          const { query } = history.location;
          const { redirect } = query as { redirect: string };
          history.push(redirect || '/');
```

### 🚑 Additional Information

**layout** on app.tsx:
```typescript
export const layout: RunTimeLayoutConfig = ({initialState}) => {
  return {
    logo,
    rightContentRender: () => <RightContent/>,
    disableContentMargin: false,
    footerRender: () => <Footer/>,
    onPageChange: () => {
      // If not logged in, redirect to login
      if (!initialState?.currentUser?.uuid && history.location.pathname !== loginPath && history.location.pathname.indexOf('/public') < 0) {
        const {hash, href} = location;
        if (hash !== `#${loginPath}`) {
          history.push({
            pathname: loginPath,
            query: {
              redirect: href
            }
          });
        } else {
          history.push(loginPath);
        }
      }
    },
    menuHeaderRender: undefined,
    unAccessible: <Exception403/>,
    ...initialState?.settings,
  };
};
```

**Comment by renanwilliam** [comment]
Found the problem. I have overwrited some body properties in a custom css:

```css
body{
  background-image: url('/login-background.webp');
  background-repeat: no-repeat;
  background-size: cover;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-pack: center;
  -ms-flex-pack: center;
  justify-content: center;
  -webkit-box-align: center;
  -ms-flex-align: center;
  align-items: center;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -ms-flex-direction: column;
  flex-direction: column;
  height: 100vh;
  width: 100%;
  margin: 0;
}
```
